### ISSUE TITLE
Support iterating over PyObject not working

### ISSUE THREAD

**Issue by hoangpq** [denosaurs/deno_python#10]
Hi.

I not sure about "support iterating over PyObject" PR  but after the playground

PR: https://github.com/denosaurs/deno_python/pull/6/files

<img width="956" alt="Screen Shot 2022-02-15 at 12 19 12 AM" src="https://user-images.githubusercontent.com/5939997/153914335-975c3fd8-42df-4461-8491-51e47505acff.png">

As you can see `test` method return a list of int but still throw error that list is not iterable.

Environment:

Deno 1.18.2 (release, x86_64-apple-darwin)
v8 9.8.177.6
Typescript 4.5.2
Python 3.9
OS: MacOS Big Sur

**Comment by DjDeveloperr** [comment]
Hey, I didn't define the `Symbol.iterator` function on Proxied PyObject which causes iterating to not work on proxies 😅
Making PR in few moments to add it and a test case for the same (sorry for the delayed response I was kinda burnt out and sick)

**Comment by DjDeveloperr** [comment]
Fix released in 0.1.3

**Comment by hoangpq** [comment]
Thanks, @DjDeveloperr, take care of yourself 👍
