### ISSUE TITLE
`findLib` is slow on Windows

### ISSUE THREAD

**Issue by DjDeveloperr** [denosaurs/deno_python#14]
Not sure about other platforms, but `findLib` is pretty slow on Windows. It takes up 2s at startup on my machine. I think we should not use a command (`where`) to look for Python, instead try to load all supported Python versions in order and return the suitable library.

**Comment by hoangpq** [comment]
@DjDeveloperr Working find on Darwin.

```typescript
console.time("findLib");
const lib = Deno.env.get("DENO_PYTHON_PATH") ?? await findLib();
console.timeEnd("findLib");
```

findLib: 2ms
