### ISSUE TITLE
[Question] Is the any way to call TS/JS function in Python land?

### ISSUE THREAD

**Issue by hoangpq** [denosaurs/deno_python#16]
Hi @eliassjogreen @DjDeveloperr 

I'm trying to access TS/JS function by writing FFI in Rust and getting JS/TS function in v8 Context.

Unfortunately, rusty_v8 does not expose Isolate::Get_Current() method 
https://github.com/denoland/rusty_v8/issues/469.

Is there any way to call TS/JS function in Python land?

**Comment by DjDeveloperr** [comment]
No, there currently is not. FFI callback support would be needed for that (to create a C function pointer for wrapping in Python function).
Ref: https://github.com/denoland/deno/pull/13162 https://github.com/denoland/deno/issues/13573

**Comment by hoangpq** [comment]
Yay. Thanks, @DjDeveloperr.
