### ISSUE TITLE
Support slices and ellipsis

### ISSUE THREAD

**Issue by tjosepo** [denosaurs/deno_python#18]
There's currently no way to use slices (`:`) or ellipsis (`...`).

Would something similar to `NamedArgument` be able to solve this?

```js
import { python, Slice } from "https://deno.land/x/python@0.1.4/mod.ts";

const np = python.import("numpy");
const slice = np.array([1, 2, 3]).__getitem__(new Slice(1,3,null)); // equivalent to [1:3]
console.log(slice); // returns [2, 3]
```

**Comment by DjDeveloperr** [comment]
Did you use the PySlice_* APIs?

**Comment by tjosepo** [comment]
> Did you use the PySlice_* APIs?

Yes. `PySlice_New` for creating the slice, then `PyObject_Get/SetItem`.

For multidimensional slices, `PySlice_New` for each slice, then merge them using `PyTuple_Pack`, then `PyObject_Get/SetItem`.

> sorry for delay I'm just really busy with school

No worries! I should be studying for finals too 😅 instead I'm procrastinating and doing this.

I already worked on it, I'll clean up my code and try to open a PR before the end of the week. No need to review it immediately.

**Comment by tjosepo** [comment]
> Did you use the PySlice_* APIs?

Yes. `PySlice_New` for creating the slice, then `PyObject_Get/SetItem`.

For multidimensional slices, `PySlice_New` for each slice, then merge them using `PyTuple_Pack`, then `PyObject_Get/SetItem`.

> sorry for delay I'm just really busy with school

No worries! I should be studying for finals too 😅 instead I'm procrastinating and doing this.

I already worked on it, I'll clean up my code and try to open a PR before the end of the week. No need to review it immediately.
