### ISSUE TITLE
Be explicit in doc about what exactly DENO_PYTHON_PATH should point to, and the need of --unstable flag

### ISSUE THREAD

**Issue by fvilante** [denosaurs/deno_python#22]
It's not clear in doc (README.md) whether "DENO_PYTHON_PATH" (in a Windows 10 context) should point to the python DIRECTORY, or to the python.exe FILE, or to anything else.

In my case pointing to python.dll solved the problem. (More precisely "C:\Python310\python310.dll").

It would be also worth to mention in docs that the flag "--unstable" IS ABSOLUTELY NECESSARY.

Thank you for this amazing piece of code you are working on!

**Comment by DjDeveloperr** [comment]
Updated the README to include this info explicitly.

> Thank you for this amazing piece of code you are working on!

Thanks for the kind words 😄
