### ISSUE TITLE
PythonError type name is lost

### ISSUE THREAD

**Issue by s-cork** [denosaurs/deno_python#32]
value.toString in python for an exception loses the type information which is particularly handy for debugging

suggested alternative

```ts
  let errorMessage = (value ?? type).getAttr("__repr__").call().toString();
```

<a href="https://dashboard.polar.sh/denosaurs/deno_python/issues/32">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/denosaurs/deno_python/issues/32/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/denosaurs/deno_python/issues/32/pledge.svg">
</picture>
</a>

**Comment by eliassjogreen** [comment]
Closed by #42. `PythonError`s now contain the https://github.com/denosaurs/deno_python/blob/main/src/python.ts#L793-L795 type, value and traceback as `PyObject`s making it easy to actually catch and use the thrown value and type.
