### ISSUE TITLE
problem with javascript unicode characters sent as arguments to python

### ISSUE THREAD

**Issue by s-cork** [denosaurs/deno_python#33]
reproduction examples

```ts
> python.builtins.eval("'中文'#foo", {})
中文
> python.builtins.eval("'中文'", {})
Uncaught PythonError: ('EOL while scanning string literal', ('<string>', 1, 3, "'中文"))
> python.builtins.str("'中文'#foo")
'中文'
python.builtins.str("'中文'")
'中
> python.builtins.str("中文")
Uncaught PythonError: <class 'str'> returned a result with an error set
```

<a href="https://dashboard.polar.sh/denosaurs/deno_python/issues/33">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/denosaurs/deno_python/issues/33/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/denosaurs/deno_python/issues/33/pledge.svg">
</picture>
</a>

**Comment by eliassjogreen** [comment]
Looking into this it seems like the C-API `PyUnicode_DecodeUTF8` expects the byte size of the string instead of the char length of the string which is why characters which takes more than one byte breaks it. Will try to fix it later if I have time.
