### ISSUE TITLE
tkinter can be used with deno_python ?

### ISSUE THREAD

**Issue by elycheikhsmail** [denosaurs/deno_python#4]

**Comment by DjDeveloperr** [comment]
I was able to open a simple window using tkinter, however it may not be very usable considering we do not support callbacks, which are crucial for events, etc. Maybe after FFI supports callbacks https://github.com/denoland/deno/pull/13162 we can try adding support for that in this module.

![image](https://user-images.githubusercontent.com/43033058/147768525-d8c31d40-a48c-4ac8-b5a2-b23c5669697c.png)

**Comment by elycheikhsmail** [comment]
@DjDeveloperr  thank you

**Comment by elycheikhsmail** [comment]
I think when ffi callback supported in deno it will be poosible to use tkinter in deno wihout deno_python

**Comment by DjDeveloperr** [comment]
Yes it would be possible, `Tk` has C API that Deno FFI can consume, but of course it'll need callback support to do anything useful with it.
