### ISSUE TITLE
should void also be added to PythonConvertible 

### ISSUE THREAD

**Issue by sigmaSd** [denosaurs/deno_python#56]
Currently this `python.callback((_, _)` always gives a type error, becuase it seems the jscallback default to `void` which is not a PythonConvertible. https://github.com/denosaurs/deno_python/blob/025e9dab00e916e4bfa697a6f23298fd75e250da/src/python.ts#L61

Currently the workaround is to always annotate the type, mostly like this `python.callback((_, button: Gtk_.ToggleButton): undefined`

If void can be add as a PythonConvertible this would remove this unnecessary typing.

**Comment by eliassjogreen** [comment]
I think that makes sense.
